/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package workflow_test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        System.out.println("This Unite tested completed succesfully");
    }

    @Test void testHasFailed(){
        assertEquals(1, 1);
    }
}
